# Generated by Django 4.2.15 on 2024-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
