# Generated by Django 4.2.15 on 2024-08-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='Model_name',
        ),
    ]
