# Generated by Django 4.2.15 on 2024-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_rename_product_name_product_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Model_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
