# Generated by Django 4.2.15 on 2024-08-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
