# Generated by Django 4.2.15 on 2024-09-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_selected_course'),
        ('Product', '0005_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateField(null=True)),
                ('Quantity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('GST', models.FloatField(default=0)),
                ('Final_price', models.IntegerField(default=0)),
                ('Customer_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('Product_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
            ],
        ),
    ]
