# Generated by Django 4.2.15 on 2024-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_signup_password_remove_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='Username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
